CREATE TABLE IF NOT EXISTS URL_db(
    hashkey PRIMARY KEY VARCHAR  ,  
    shortURL text NOT NULL,
    longURL text NOT NULL,
    CreatedOn DATE NOT NULL DEFAULT CURRENT_DATE ,
    ExpiresOn DATE NOT NULL DEFAULT (CURRENT_DATE + interval '90 days') ,
    LastVisited DATE NOT NULL DEFAULT CURRENT_DATE ,

)